### ISSUE TITLE
Add flake8 Python Linting

### ISSUE THREAD

**Issue by NicholasChoong** [codersforcauses/software-engineering-practices-demo-2022-summer#9]
## Task
Fit the repository with an CI script that will run automatically on pull request to make sure that code fits the flake8 code standards.

## Acceptance Criteria
- CI succeeds when code meets standards
- CI fails when code does not meet standards

## Answer
Add the `flake8_py3` step to the file `.github/workflows/ci.yml` such that the end result will now be
```yml
name: Python package

on:
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: false
        default: "warning"

jobs:
  flake8_py3:
    name: "Linting with Flake8"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: "Install flake8"
        run: pip install flake8

      - name: "Install flake8-django"
        run: pip install flake8-django

      - name: "Run flake8"
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: flake8
          run: flake8 --max-line-length 150 .
```
